name: Release
on:
  push:
    branches:
    - main
    - master
jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Bump version and tag
      uses: mathieudutour/github-tag-action@v5.5
      id: tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push containers
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.new_tag }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        release_name: Release ${{ steps.tag.outputs.new_version }}
        body: |
          Changes in this release:

          ${{ steps.tag.outputs.changelog }}

          Docker image: ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.new_tag }}
        draft: false
        prerelease: false
